### ISSUE TITLE
Will These Settings Work With .desktop files?

### ISSUE THREAD

**Issue by 0pLuS0** [artemsen/swayimg#302]
Hi,

I'm running CachyOS, hyprland 0.49.0-1 and 4.2-1.1.

I have the config at; ~/.config/swayimg/config

I noticed if I run; ```swayimg -r /home/$USER/*``` the settings are being respected;

position = 800,300
size = 1024,768

But if I run swayimg from a .desktop file, I click on in the rofi menu, they are not being respected, swayimg opens full screen. 

[Desktop Entry]
Name=swayimg
Exec=swayimg -r /home/$USER/Pictures/*
Terminal=false
Type=Application
Icon=image-viewer
Comment=Image Viewer for Wayland
Categories=Graphics;

But if I run swayimg from the cmd line and then try it at the rofi menu shortcut, sometimes it does respect the position and size, but at some point it goes back to full screen.

Either I'm getting old or stupid LOL, but I swear man swayimg reads as -p --position and -w --size for valid flags, but they don't work.

I thought I'd force the position and size, but no luck

swayimg -p 800,300 -w 1024,768 -r /home/$USER/Pictures/*
swayimg: invalid option -- 'p'

swayimg --position=800,300 --size=1024,768 -r /home/$USER/Pictures/*    
swayimg: unrecognized option '--position=800,300'

THANKS

**Comment by 0pLuS0** [comment]
I also tried running it from a shell script

[Desktop Entry]
Name=swayimg
```Exec=~/.config/swayimg/run.sh```
Terminal=false
Type=Application
Icon=image-viewer
Comment=Image Viewer for Wayland
Categories=Graphics;

```run.sh```
#!/bin/bash
swayimg --gallery /home/$USER/Pictures/*

It still won't respect the size/position, it opens full screen...

But if I play around with it, running it from the cli, every so often it then behaves, but for some reason it will revert back too.

hmm

**Comment by artemsen** [comment]
> swayimg: unrecognized option '--position=800,300'

[Fixed](https://github.com/artemsen/swayimg/commit/7b1dcf98a77b81131f84f1e6bb71ae99be017497) in master.

**Comment by 0pLuS0** [comment]
There's a git version of swayimg I just grabbed and the -p position works now;

https://aur.archlinux.org/packages/swayimg-git

pacman -Qi swayimg                                                  
Installed From  : None
Name            : swayimg-git
```Version         : 4.2.22-1```
Description     : Image viewer for Wayland
Architecture    : x86_64
URL             : https://github.com/artemsen/swayimg


I'm running the .desktop as;

```Exec=~/.config/swayimg/run.sh```

And the run.sh as;

```swayimg --gallery /home/$USER/Pictures/*```

It seems to be opening up ok from the config settings I'm using now;

position = 700,300
size = 1200,768
compositor = yes - I turned this back on...

Hopefully this master change helps here with keeping position/size when opening from the rofi menu.

THANKS

**Comment by 0pLuS0** [comment]
I spoke to soon, it's still not respecting the config settings.

But now, I have seen something triggering this, which is really odd.

If I have no windows open on any desktops swayimg always opens full screen.

But if I open an app, doesn't matter, any app will do.

Then I move over to another desktop and open swayimg from the rofi menu, it THEN respects the config and opens correctly, with these settings;

position = 700,300
size = 1200,768
compositor = yes

If I turn the compositor = no it will still open full screen.

Hmmm this is odd, so I don't get why I need a window open on another desktop to have it open to the position and size I have in the config.

THANKS

**Comment by artemsen** [comment]
When compositor integration is enabled, swayimg creates an "overlay" above the currently active window. If you don't have any windows then the active window is a desktop, so you have full screen window.
This mode is primarily intended to use with terminal.

**Comment by 0pLuS0** [comment]
You said; When compositor integration is enabled

```compositor = yes```?

So if compositor = no is set this can be done?

Is it possible to change this, so it can be launched from a menu instead of a terminal?

Hmm must be a way around this, trick it with thinking there's a dummy window, or launch a term into /dev/null 

hmm

THANKS

**Comment by artemsen** [comment]
`compositor` option allows swayimg to manage the window position. If you don't need this - just set it to `no`.
If you need different behavior in different scenarios, use [-c](https://github.com/artemsen/swayimg/blob/042c55e74750edb7f83f68b8223890bc1809ff2e/extra/swayimg.1.scd?plain=1#L78) to override config parameters: `swayimg -c general.compositor=no`

**Comment by 0pLuS0** [comment]
Hi @artemsen 

Sorry I don't understand...

I would like to have swayimg open in a position and size, either from the config'

[general]
position = 700,300 
size = 1200,768

Or I run a cmd to a shell file;

swayimg -p 700,300 -w 1200,768 -r /home/$USER/Pictures/*

I also don't understand if -c flag helps with any of this?

THANKS

**Comment by artemsen** [comment]
> Sorry I don't understand...

Most likely it is I who do not understand =)
Please, describe step by step how to reproduce the problem and real/expected results.

**Comment by 0pLuS0** [comment]
Set up swayimg with a menu entry in rofi.

[Desktop Entry]
Name=swayimg
Exec=~/.config/swayimg/run.sh
Terminal=false
Type=Application
Icon=image-viewer
Comment=Image Viewer for Wayland
Categories=Graphics;

In the shell script place the cmds;

~/.config/swayimg/run.sh

#!/bin/bash
swayimg -r /home/$USER/Pictures/*

Now run swayimg from the rofi menu;

![Image](https://github.com/user-attachments/assets/307df610-346e-454d-9c6b-dbd5f5171ec1)

And now it appears as expected, to size and position;

![Image](https://github.com/user-attachments/assets/bce8486f-cd2a-46ba-bad5-0b581c58a4de)

**Comment by artemsen** [comment]
> And now it appears as expected, to size and position;

So what's the problem?

**Comment by 0pLuS0** [comment]
As you mentioned;

```
When compositor integration is enabled, swayimg creates an "overlay" above the currently active window. 
If you don't have any windows then the active window is a desktop, so you have full screen window.
This mode is primarily intended to use with terminal.
```

So I can't simply run swayimg from a rofi menu entry and have it look like this, unless another window is open on another desktop.

I was hoping swayimg could be run without any other windows needing to be open in Hyprland.

THANKS

**Comment by artemsen** [comment]
> I was hoping swayimg could be run without any other windows needing to be open in Hyprland.

Swayimg doesn't need any other windows to run. If you want to use it as usual application (without managing the window position) - just set `compositor` to `no`. If you want to manage window position - set it to `yes` and specify position in config, if you don't set set position, then swayimg will create an overlay for currently active window. If you don't have any windows - it will use the entire screen.

**Comment by 0pLuS0** [comment]
Hi @artemsen 

These are my settings;

position = 700,300
size = 1200,768
compositor = yes

It does not respect these settings, as I mentioned before, if I don't open a window/app on another desktop, swayimg opens in full screen, if I open it from the menu.

Here is my config file... THANKS

[config.txt](https://github.com/user-attachments/files/20793551/config.txt)

**Comment by 0pLuS0** [comment]
So from what you said;

```If you don't have any windows - it will use the entire screen.```

Yes, if I don't have any windows it's ```Full Screen```

That is the problem, if it's possible to run it as position = 700,300 size = 1200,768 compositor = yes with no windows, only swayimg.

THANKS

**Comment by artemsen** [comment]
Sorry, but I can't help you.
Hyprland support is experimental. I don't use it myself, so there may be problems, especially with multi-display configurations (I didn't check it at all).
You can completely disable the integration mode and use swayimg as usual application.
Or you can create a new bug report and describe the problem there so that it doesn't get lost. Maybe one of the Hyprland users will fix this.

**Comment by 0pLuS0** [comment]
Thanks for your time @artemsen it is greatly appreciated.

P.S. I'll make a bug report later...
